//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHacker.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_English() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniHacker.Properties.Language_English", typeof(Language_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Patch all versions of Unity and UnityHub.  
        /// 
        ///If patch fails, please submit unity.exe binary file or Unity Hub version number on Github issue.   的本地化字符串。
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This application is not Unity.exe or Unity Hub.exe 的本地化字符串。
        /// </summary>
        internal static string non_unity {
            get {
                return ResourceManager.GetString("non_unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotSupport Patch 的本地化字符串。
        /// </summary>
        internal static string NotSupport {
            get {
                return ResourceManager.GetString("NotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PATCH 的本地化字符串。
        /// </summary>
        internal static string patch_btn {
            get {
                return ResourceManager.GetString("patch_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patch failed! 的本地化字符串。
        /// </summary>
        internal static string patch_fail {
            get {
                return ResourceManager.GetString("patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully patched! 的本地化字符串。
        /// </summary>
        internal static string patch_success {
            get {
                return ResourceManager.GetString("patch_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has been patched 的本地化字符串。
        /// </summary>
        internal static string Patched {
            get {
                return ResourceManager.GetString("Patched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is running and the patch may fail! 的本地化字符串。
        /// </summary>
        internal static string process_occupy {
            get {
                return ResourceManager.GetString("process_occupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: 的本地化字符串。
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support Patch 的本地化字符串。
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag Unity.exe or Unity Hub.exe to the window 的本地化字符串。
        /// </summary>
        internal static string tips {
            get {
                return ResourceManager.GetString("tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
