//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniHacker.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_Chinese() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniHacker.Assets.Language_Chinese", typeof(Language_Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 破解所有版本的Unity和UnityHub.
        ///
        ///如果破解失败，请在Github issue中提交Unity文件或UnityHub的版本号. 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该程序不是Unity或Unity Hub 的本地化字符串。
        /// </summary>
        internal static string Non_unity {
            get {
                return ResourceManager.GetString("Non_unity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持破解 的本地化字符串。
        /// </summary>
        internal static string NotSupport {
            get {
                return ResourceManager.GetString("NotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 破 解 的本地化字符串。
        /// </summary>
        internal static string Patch_btn {
            get {
                return ResourceManager.GetString("Patch_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 破解失败，请按描述提交该问题！ 的本地化字符串。
        /// </summary>
        internal static string Patch_fail {
            get {
                return ResourceManager.GetString("Patch_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 破解成功！ 的本地化字符串。
        /// </summary>
        internal static string Patch_success {
            get {
                return ResourceManager.GetString("Patch_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已破解 的本地化字符串。
        /// </summary>
        internal static string Patched {
            get {
                return ResourceManager.GetString("Patched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 正在运行中，可能会破解失败！ 的本地化字符串。
        /// </summary>
        internal static string Process_occupy {
            get {
                return ResourceManager.GetString("Process_occupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 Unity 或 Unity Hub. 的本地化字符串。
        /// </summary>
        internal static string SelectTips {
            get {
                return ResourceManager.GetString("SelectTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国内特供版不支持破解 的本地化字符串。
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件状态： 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持破解 的本地化字符串。
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本： 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
